### ISSUE TITLE
Connect to time to merge service with kebechet and serve results in our repos

### ISSUE THREAD

**Issue by MichaelClifford** [aicoe-aiops/ocp-ci-analysis#430] opened 2021-10-21 18:37 UTC
We currently have a model served that predicts time to merge for PR's in OCP/origins repo. Next steps are to integrate it with  kebechet so that it can provide its predictions as comments in newly opened PR's.

**Comment by chauhankaranraj** [comment] 2022-03-07 12:00
@MichaelClifford can this be closed as a duplicate of #362?

**Closed** 2022-03-07 16:30 UTC
