### ISSUE TITLE
Update the ocp-ci-analysis image on JH

### ISSUE THREAD

**Issue by aakankshaduggal** [aicoe-aiops/ocp-ci-analysis#343] opened 2021-08-17 16:19 UTC
Update the image has on JupyterHub with the latest changes.

**Comment by MichaelClifford** [comment] 2021-08-17 17:13
I think this may be a duplicate of  https://github.com/aicoe-aiops/ocp-ci-analysis/issues/335

**Closed** 2021-08-17 18:08 UTC
